# Generated by Django 4.0 on 2024-04-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_auto_20240426_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='assignedDoctorId',
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='education',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointmentDate',
            field=models.DateField(default=None, null=True),
        ),
    ]
